# Generated by Django 4.2.7 on 2023-11-26 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Производитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.JSONField(blank=True, default=2, verbose_name='Характеристики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
