# Generated by Django 4.2.7 on 2023-11-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_manufacturer_product_properties_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_paths',
            field=models.JSONField(blank=True, default=1, verbose_name='Список изображений'),
            preserve_default=False,
        ),
    ]
